"""
Bicep template generator for Azure deployment
"""
from typing import Dict, Any
from datetime import datetime

class BicepGenerator:
    """Generate Bicep templates for Azure deployment"""
    
    def __init__(self, project: Dict[str, Any], config: Dict[str, Any]):
        self.project = project
        self.config = config
    
    def generate_bicep(self) -> Dict[str, str]:
        """Generate Bicep template files"""
        
        main_bicep = self._generate_main_bicep()
        parameters_file = self._generate_parameters()
        readme = self._generate_deployment_readme()
        
        return {
            'main.bicep': main_bicep,
            'parameters.json': parameters_file,
            'README.md': readme
        }
    
    def _generate_main_bicep(self) -> str:
        """Generate main Bicep template"""
        
        project_name = self.project['name'].lower().replace(' ', '-')
        location = self.config.get('location', 'eastus')
        cpu = self.config.get('cpu_cores', 0.5)
        memory = self.config.get('memory_gb', 1.0)
        min_replicas = self.config.get('min_replicas', 1)
        max_replicas = self.config.get('max_replicas', 10)
        
        template = f"""// MAF Agent Builder - Generated Bicep Template
// Project: {self.project['name']}
// Generated: Auto-generated by MAF Agent Builder

@description('Location for all resources')
param location string = '{location}'

@description('Name of the Container Apps environment')
param environmentName string = '{project_name}-env'

@description('Name of the container app')
param containerAppName string = '{project_name}-app'

@description('Container image')
param containerImage string = 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'

@description('Minimum number of replicas')
@minValue(0)
@maxValue(30)
param minReplicas int = {min_replicas}

@description('Maximum number of replicas')
@minValue(1)
@maxValue(30)
param maxReplicas int = {max_replicas}

// Log Analytics Workspace
resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2022-10-01' = {{
  name: '${{environmentName}}-logs'
  location: location
  properties: {{
    sku: {{
      name: 'PerGB2018'
    }}
    retentionInDays: 30
  }}
}}

// Container Apps Environment
resource environment 'Microsoft.App/managedEnvironments@2023-05-01' = {{
  name: environmentName
  location: location
  properties: {{
    appLogsConfiguration: {{
      destination: 'log-analytics'
      logAnalyticsConfiguration: {{
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }}
    }}
  }}
}}

// Container App
resource containerApp 'Microsoft.App/containerApps@2023-05-01' = {{
  name: containerAppName
  location: location
  properties: {{
    managedEnvironmentId: environment.id
    configuration: {{
      ingress: {{
        external: true
        targetPort: 8501
        transport: 'auto'
        allowInsecure: false
      }}
      secrets: [
        {{
          name: 'openai-api-key'
          value: 'PLACEHOLDER'
        }}
      ]
    }}
    template: {{
      containers: [
        {{
          name: 'main'
          image: containerImage
          resources: {{
            cpu: json('{cpu}')
            memory: '{memory}Gi'
          }}
          env: [
            {{
              name: 'OPENAI_API_KEY'
              secretRef: 'openai-api-key'
            }}
          ]
        }}
      ]
      scale: {{
        minReplicas: minReplicas
        maxReplicas: maxReplicas
        rules: [
          {{
            name: 'http-scaling'
            http: {{
              metadata: {{
                concurrentRequests: '10'
              }}
            }}
          }}
        ]
      }}
    }}
  }}
}}

output containerAppFQDN string = containerApp.properties.configuration.ingress.fqdn
output containerAppUrl string = 'https://${{containerApp.properties.configuration.ingress.fqdn}}'
"""
        
        return template
    
    def _generate_parameters(self) -> str:
        """Generate parameters file"""
        
        import json
        
        params = {
            "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
            "contentVersion": "1.0.0.0",
            "parameters": {
                "location": {
                    "value": self.config.get('location', 'eastus')
                }
            }
        }
        
        return json.dumps(params, indent=2)
    
    def generate_cli_script(self) -> Dict[str, str]:
        """Generate Azure CLI deployment script"""
        
        project_name = self.project['name'].lower().replace(' ', '-')
        rg = self.config.get('resource_group', 'maf-agents-rg')
        location = self.config.get('location', 'eastus')
        
        script = f"""#!/bin/bash
# MAF Agent Builder - Azure CLI Deployment Script
# Project: {self.project['name']}

set -e

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${{BASH_SOURCE[0]}}" )" && pwd )"
cd "$SCRIPT_DIR"

# Variables
RESOURCE_GROUP="{rg}"
LOCATION="{location}"
PROJECT_NAME="{project_name}"

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[0;33m'
NC='\\033[0m' # No Color

echo "🚀 Starting deployment of $PROJECT_NAME..."
echo ""

# Check if deployment files exist
if [ ! -f "main.bicep" ]; then
    echo "${{RED}}❌ Error: main.bicep not found in current directory${{NC}}"
    echo "Current directory: $(pwd)"
    echo "Please ensure you're running this script from the deployment folder."
    exit 1
fi

if [ ! -f "parameters.json" ]; then
    echo "${{YELLOW}}⚠️  Warning: parameters.json not found, using default parameters${{NC}}"
fi

# Check Azure CLI
if ! command -v az &> /dev/null; then
    echo "${{RED}}❌ Azure CLI not found. Please install it first.${{NC}}"
    echo "Install from: https://docs.microsoft.com/cli/azure/install-azure-cli"
    exit 1
fi

# Check login status
echo "Checking Azure login status..."
if ! az account show &> /dev/null; then
    echo "${{RED}}❌ Not logged in to Azure. Please run: az login${{NC}}"
    exit 1
fi

# Display current subscription
SUBSCRIPTION=$(az account show --query name -o tsv)
echo "${{GREEN}}✅ Logged in to subscription: $SUBSCRIPTION${{NC}}"
echo ""

# Create resource group
echo "📦 Creating resource group..."
az group create \\
    --name $RESOURCE_GROUP \\
    --location $LOCATION \\
    --output none

echo "${{GREEN}}✅ Resource group created${{NC}}"
echo ""

# Deploy Bicep template
echo "🏗️  Deploying infrastructure..."
echo "   Resource Group: $RESOURCE_GROUP"
echo "   Location: $LOCATION"
echo "   Template: main.bicep"
echo ""

if [ -f "parameters.json" ]; then
    az deployment group create \\
        --resource-group $RESOURCE_GROUP \\
        --template-file main.bicep \\
        --parameters parameters.json \\
        --output json > deployment-output.json
else
    az deployment group create \\
        --resource-group $RESOURCE_GROUP \\
        --template-file main.bicep \\
        --output json > deployment-output.json
fi

if [ $? -eq 0 ]; then
    echo "${{GREEN}}✅ Infrastructure deployed successfully${{NC}}"
else
    echo "${{RED}}❌ Deployment failed. Check deployment-output.json for details${{NC}}"
    exit 1
fi
echo ""

# Get the application URL
echo "🔍 Getting application URL..."
APP_URL=$(az deployment group show \\
    --resource-group $RESOURCE_GROUP \\
    --name main \\
    --query properties.outputs.containerAppUrl.value \\
    --output tsv)

echo ""
echo "${{GREEN}}🎉 Deployment complete!${{NC}}"
echo ""
echo "Application URL: $APP_URL"
echo ""
echo "To view logs:"
echo "  az containerapp logs show --name ${{PROJECT_NAME}}-app --resource-group $RESOURCE_GROUP --follow"
"""
        
        return {
            'deploy.sh': script
        }
    
    def generate_powershell_script(self) -> Dict[str, str]:
        """Generate PowerShell deployment script"""
        
        project_name = self.project['name'].lower().replace(' ', '-')
        rg = self.config.get('resource_group', 'maf-agents-rg')
        location = self.config.get('location', 'eastus')
        
        script = f"""# MAF Agent Builder - PowerShell Deployment Script
# Project: {self.project['name']}

$ErrorActionPreference = "Stop"

# Get the directory where this script is located
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ScriptDir

# Variables
$ResourceGroup = "{rg}"
$Location = "{location}"
$ProjectName = "{project_name}"

Write-Host "🚀 Starting deployment of $ProjectName..." -ForegroundColor Cyan
Write-Host ""

# Check if deployment files exist
if (!(Test-Path "main.bicep")) {{
    Write-Host "❌ Error: main.bicep not found in current directory" -ForegroundColor Red
    Write-Host "Current directory: $(Get-Location)"
    Write-Host "Please ensure you're running this script from the deployment folder."
    exit 1
}}

if (!(Test-Path "parameters.json")) {{
    Write-Host "⚠️  Warning: parameters.json not found, using default parameters" -ForegroundColor Yellow
}}

# Check Azure CLI
if (!(Get-Command az -ErrorAction SilentlyContinue)) {{
    Write-Host "❌ Azure CLI not found. Please install it first." -ForegroundColor Red
    Write-Host "Install from: https://docs.microsoft.com/cli/azure/install-azure-cli"
    exit 1
}}

# Check login status
Write-Host "Checking Azure login status..."
try {{
    $null = az account show 2>&1
    if ($LASTEXITCODE -ne 0) {{
        throw "Not logged in"
    }}
}} catch {{
    Write-Host "❌ Not logged in to Azure. Please run: az login" -ForegroundColor Red
    exit 1
}}

# Display current subscription
$Subscription = az account show --query name -o tsv
Write-Host "✅ Logged in to subscription: $Subscription" -ForegroundColor Green
Write-Host ""

# Create resource group
Write-Host "📦 Creating resource group..."
az group create `
    --name $ResourceGroup `
    --location $Location `
    --output none

Write-Host "✅ Resource group created" -ForegroundColor Green
Write-Host ""

# Deploy Bicep template
Write-Host "🏗️  Deploying infrastructure..."
Write-Host "   Resource Group: $ResourceGroup"
Write-Host "   Location: $Location"
Write-Host "   Template: main.bicep"
Write-Host ""

try {{
    if (Test-Path "parameters.json") {{
        az deployment group create `
            --resource-group $ResourceGroup `
            --template-file main.bicep `
            --parameters parameters.json `
            --output json | Out-File -FilePath deployment-output.json
    }} else {{
        az deployment group create `
            --resource-group $ResourceGroup `
            --template-file main.bicep `
            --output json | Out-File -FilePath deployment-output.json
    }}
    
    if ($LASTEXITCODE -eq 0) {{
        Write-Host "✅ Infrastructure deployed successfully" -ForegroundColor Green
    }} else {{
        throw "Deployment failed"
    }}
}} catch {{
    Write-Host "❌ Deployment failed. Check deployment-output.json for details" -ForegroundColor Red
    exit 1
}}
Write-Host ""

# Get the application URL
Write-Host "🔍 Getting application URL..."
$AppUrl = az deployment group show `
    --resource-group $ResourceGroup `
    --name main `
    --query properties.outputs.containerAppUrl.value `
    --output tsv

Write-Host ""
Write-Host "🎉 Deployment complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Application URL: $AppUrl"
Write-Host ""
Write-Host "To view logs:"
Write-Host "  az containerapp logs show --name $ProjectName-app --resource-group $ResourceGroup --follow"
"""
        
        return {
            'deploy.ps1': script
        }
    
    def generate_terraform(self) -> Dict[str, str]:
        """Generate Terraform configuration (preview)"""
        
        project_name = self.project['name'].lower().replace(' ', '-')
        
        main_tf = f"""# MAF Agent Builder - Terraform Configuration (Preview)
# Project: {self.project['name']}

terraform {{
  required_providers {{
    azurerm = {{
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }}
  }}
}}

provider "azurerm" {{
  features {{}}
}}

resource "azurerm_resource_group" "main" {{
  name     = var.resource_group_name
  location = var.location
}}

resource "azurerm_log_analytics_workspace" "main" {{
  name                = "${{var.project_name}}-logs"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}}

resource "azurerm_container_app_environment" "main" {{
  name                       = "${{var.project_name}}-env"
  location                   = azurerm_resource_group.main.location
  resource_group_name        = azurerm_resource_group.main.name
  log_analytics_workspace_id = azurerm_log_analytics_workspace.main.id
}}

resource "azurerm_container_app" "main" {{
  name                         = "${{var.project_name}}-app"
  container_app_environment_id = azurerm_container_app_environment.main.id
  resource_group_name          = azurerm_resource_group.main.name
  revision_mode                = "Single"

  template {{
    container {{
      name   = "main"
      image  = var.container_image
      cpu    = var.cpu_cores
      memory = "${{var.memory_gb}}Gi"

      env {{
        name        = "OPENAI_API_KEY"
        secret_name = "openai-api-key"
      }}
    }}

    min_replicas = var.min_replicas
    max_replicas = var.max_replicas
  }}

  ingress {{
    external_enabled = true
    target_port      = 8501
    transport        = "auto"
  }}

  secret {{
    name  = "openai-api-key"
    value = var.openai_api_key
  }}
}}

output "container_app_url" {{
  value = "https://${{azurerm_container_app.main.latest_revision_fqdn}}"
}}
"""
        
        variables_tf = """variable "resource_group_name" {
  description = "Name of the resource group"
  type        = string
}

variable "location" {
  description = "Azure region"
  type        = string
  default     = "eastus"
}

variable "project_name" {
  description = "Project name"
  type        = string
}

variable "container_image" {
  description = "Container image"
  type        = string
}

variable "cpu_cores" {
  description = "CPU cores"
  type        = number
  default     = 0.5
}

variable "memory_gb" {
  description = "Memory in GB"
  type        = number
  default     = 1.0
}

variable "min_replicas" {
  description = "Minimum replicas"
  type        = number
  default     = 1
}

variable "max_replicas" {
  description = "Maximum replicas"
  type        = number
  default     = 10
}

variable "openai_api_key" {
  description = "OpenAI API Key"
  type        = string
  sensitive   = true
}
"""
        
        return {
            'main.tf': main_tf,
            'variables.tf': variables_tf
        }
    
    def _generate_deployment_readme(self) -> str:
        """Generate deployment README"""
        
        project_name = self.project['name']
        rg = self.config.get('resource_group', 'maf-agents-rg')
        location = self.config.get('location', 'eastus')
        
        readme = f"""# {project_name} - Azure Deployment Guide

**Generated by MAF Agent Builder**  
**Deployment Type**: Azure Container Apps  
**Target Region**: {location}

## 📋 Prerequisites

Before deploying, ensure you have:

- [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) installed
- An active Azure subscription
- Bicep CLI (automatically installed with Azure CLI 2.20.0+)
- Docker image built and pushed to a container registry (if using custom image)

## 🚀 Quick Start

### ⚠️ IMPORTANT: Run from Deployment Folder

**All deployment files (main.bicep, parameters.json, deploy scripts) must be in the same folder.**

Make sure you:
1. Download or save ALL deployment files to a single folder
2. Open a terminal/PowerShell in that folder
3. Run the deployment script from there

### Option 1: Using Deployment Script (Recommended)

**For Linux/Mac (Bash):**
```bash
# Navigate to the deployment folder
cd /path/to/deployment/folder

# Make script executable
chmod +x deploy.sh

# Run deployment (script will automatically use files in current directory)
./deploy.sh
```

**For Windows (PowerShell):**
```powershell
# Navigate to the deployment folder
cd C:\\path\\to\\deployment\\folder

# Run deployment (script will automatically use files in current directory)
.\\deploy.ps1
```

The script will:
- ✅ Automatically detect and use files in the current directory
- ✅ Verify all required files exist before deploying
- ✅ Change to the script's directory automatically
- ✅ Provide clear error messages if files are missing

### Option 2: Manual Deployment

**Make sure you're in the folder containing main.bicep and parameters.json!**

1. **Login to Azure**
   ```bash
   az login
   ```

2. **Set your subscription** (if you have multiple)
   ```bash
   az account list --output table
   az account set --subscription "YOUR_SUBSCRIPTION_ID"
   ```

3. **Create resource group**
   ```bash
   az group create \\
     --name {rg} \\
     --location {location}
   ```

4. **Deploy Bicep template**
   ```bash
   az deployment group create \\
     --resource-group {rg} \\
     --template-file main.bicep \\
     --parameters parameters.json
   ```

5. **Get deployment outputs**
   ```bash
   az deployment group show \\
     --resource-group {rg} \\
     --name main \\
     --query properties.outputs
   ```

## 📦 What Gets Deployed?

This deployment creates the following Azure resources:

- **Log Analytics Workspace**: For centralized logging and monitoring
- **Container Apps Environment**: Managed Kubernetes environment for running containers
- **Container App**: Your AI agent application with auto-scaling configured
- **HTTPS Endpoint**: Automatically provisioned with SSL certificate

## ⚙️ Configuration

### Environment Variables

Update these in `main.bicep` or set as secrets:

- `OPENAI_API_KEY`: Your OpenAI API key (required)
- `AZURE_OPENAI_ENDPOINT`: Azure OpenAI endpoint (if using Azure OpenAI)
- `AZURE_OPENAI_KEY`: Azure OpenAI key (if using Azure OpenAI)

### Scaling Configuration

Current settings:
- Min Replicas: {self.config.get('min_replicas', 1)}
- Max Replicas: {self.config.get('max_replicas', 10)}
- CPU: {self.config.get('cpu_cores', 0.5)} cores
- Memory: {self.config.get('memory_gb', 1.0)} GB

### Custom Domain (Optional)

To add a custom domain:

```bash
az containerapp hostname add \\
  --resource-group {rg} \\
  --name {project_name.lower().replace(' ', '-')}-app \\
  --hostname your-domain.com
```

## 🔍 Monitoring & Debugging

### View Application Logs
```bash
az containerapp logs show \\
  --name {project_name.lower().replace(' ', '-')}-app \\
  --resource-group {rg} \\
  --follow
```

### Check Application Status
```bash
az containerapp show \\
  --name {project_name.lower().replace(' ', '-')}-app \\
  --resource-group {rg} \\
  --query properties.runningStatus
```

### View Metrics in Azure Portal
1. Navigate to [Azure Portal](https://portal.azure.com)
2. Go to Resource Groups → `{rg}`
3. Click on your Container App
4. View Metrics, Logs, and Health under Monitoring section

## 🔄 Updates & Redeployment

To update your deployment:

1. Modify the Bicep template or parameters
2. Re-run the deployment command:
   ```bash
   az deployment group create \\
     --resource-group {rg} \\
     --template-file main.bicep \\
     --parameters parameters.json
   ```

## 🗑️ Cleanup

To delete all resources:

```bash
az group delete --name {rg} --yes --no-wait
```

## 🔐 Security Best Practices

1. **Never commit secrets** to version control
2. Use **Azure Key Vault** for production secrets:
   ```bash
   az keyvault create --name mykeyvault --resource-group {rg}
   az keyvault secret set --vault-name mykeyvault --name "openai-key" --value "YOUR_KEY"
   ```
3. Enable **Managed Identity** for accessing Azure resources
4. Configure **network restrictions** for production workloads

## 📚 Additional Resources

- [Azure Container Apps Documentation](https://docs.microsoft.com/azure/container-apps/)
- [Bicep Documentation](https://docs.microsoft.com/azure/azure-resource-manager/bicep/)
- [MAF Agent Builder Documentation](https://github.com/yourusername/maf-agent-builder)

## 🆘 Troubleshooting

### Issue: Deployment fails with "Subscription not found"
**Solution**: Set the correct subscription:
```bash
az account set --subscription "YOUR_SUBSCRIPTION_ID"
```

### Issue: Container fails to start
**Solution**: Check logs for errors:
```bash
az containerapp logs show --name your-app --resource-group {rg} --follow
```

### Issue: Application not accessible
**Solution**: Verify ingress settings and check application health:
```bash
az containerapp show --name your-app --resource-group {rg} --query properties.configuration.ingress
```

## 📞 Support

For issues and questions:
- GitHub Issues: [Your Repository]
- Documentation: [Your Docs]
- Community: [Your Community]

---

**Generated on**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**MAF Agent Builder**: Simplifying AI Agent Deployment
"""
        
        return readme
